name: CI

on:
  push:
    branches: [ "trunk", "feat/**" ]
  pull_request:
    branches: [ "trunk", "feat/**" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Powershell 1/5
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y wget

      - name: Install Powershell 2/5
        run: wget https://github.com/PowerShell/PowerShell/releases/download/v7.5.4/powershell_7.5.4-1.deb_amd64.deb

      - name: Install Powershell 3/5
        run: sudo dpkg -i powershell_7.5.4-1.deb_amd64.deb

      - name: Install Powershell 4/5
        run: sudo apt-get install -f

      - name: Install Powershell 5/5
        run: rm powershell_7.5.4-1.deb_amd64.deb

      - name: Running tests...
        run: pwsh -NoLogo -NonInteractive -File ./tests/test.ps1
